### ISSUE TITLE
Le symbole des ancres ne s'affiche pas sur Ubuntu 14

### ISSUE THREAD

**Issue by petitphp** [TweetPressFr/anchorpress#1]
Le symbole utilisé pour les ancres ne s'affiche pas sur Ubuntu 14 (testé avec Firefox 52 et Chrome 56). 
Le caractère ne semble pas supporté :disappointed:  :
![image](https://cloud.githubusercontent.com/assets/158572/22838886/59187fe2-efc7-11e6-98d6-ca3a0c0dddc8.png)

La ligne qui pose problème: https://github.com/TweetPressFr/anchorpress/blob/master/anchorpress.php#L75

Merci d'avance !

**Comment by TweetPressFr** [comment]
[0.4](https://github.com/TweetPressFr/anchorpress/releases/tag/0.4) fixe ça ^^
